apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '{{ .Values.secret.smtpUser }}'
      smtp_auth_username: '{{ .Values.secret.smtpUser }}'
      smtp_auth_password: '{{ .Values.secret.smtpPass }}'
      smtp_require_tls: true
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: '{{ .Values.secret.smtpUser }}'
            send_resolved: true
