apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: {{ default "ClusterIP" .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
