apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-destination
spec:
  host: {{ .Values.app.name }}
  subsets:
    {{- range .Values.versions.app }}
    - name: {{ .name }}
      labels:
        version: {{ .name }}
    {{- end }}