apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-destination
spec:
  host: {{ .Values.app.name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        # httpHeaderName: x-user-id
        # Or For simple browser testing without custom headers, use a cookie:
        httpCookie:
          name: session-cookie
          ttl: 0s
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2