apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service-route
spec:
  hosts:
    - "*" # Must match the Gateway host
  gateways:
    - app-gateway
  http:
    {{- range .Values.versions.app }}
    - match:
        - uri: { prefix: /sms }
          headers:
            cookie:
              regex: ".*version={{ .name }}.*"
      route:
        - destination:
            host: {{ $.Values.app.name }}
            subset: {{ .name }}
          headers:
            response:
              add:
                x-app-version: "{{ .name }}"
    {{- end }}
    - route:
        {{- range .Values.versions.app }}
        - destination:
            host: {{ $.Values.app.name }}
            subset: {{ .name }}
          weight: {{ .weight }}
          headers:
            response:
              set:
                Set-Cookie: "version={{ .name }}; Path=/sms; Max-Age=3600"
              add:
                x-app-version: "{{ .name }}"
        {{- end }}
