apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service-route
spec:
  hosts:
    - "*" # Must match the Gateway host
  gateways:
    - app-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}
            subset: v1
          weight: 90
        - destination:
            host: {{ .Values.app.name }}
            subset: v2
          weight: 10