{
 "title": "Requests Comparison Dashboard",
 "tags": [
  "requests-comparison",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Comparison",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_requests_total", "legendFormat": "v2 count" },
    { "expr": "sms_requests_total", "legendFormat": "v1 count" }
   ]
  },
  {
   "title": "v2 Requests Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_requests_total", "legendFormat": "SMS Requests" }
   ]
  },
  {
   "title": "v1 Requests Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sms_requests_total", "legendFormat": "SMS Requests" }
   ]
  },
  {
   "title": "Request Rate Comparison (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(app_requests_total[1m]) * 60",
     "legendFormat": "v2 Requests/min"
    },
    {
     "expr": "rate(sms_requests_total[1m]) * 60",
     "legendFormat": "v1 Requests/min"
    }
   ]
  }
 ]
}